### ISSUE TITLE
Artboard size

### ISSUE THREAD

**Issue by brunocalou** [austynmahoney/mobile-export-scripts-illustrator#12]
So, there is no artboard size specified that will generate the icons of the correct size. I tested for android, and the correct artboard size is 96 x 96 px. It should be specified somewhere in the README

**Comment by austynmahoney** [comment]
I'm not sure what you are asking here. What icons are you talking about? The baseline used is `xhdpi`, so your `xhdpi` image will be matched up with your artboard size.

**Comment by brunocalou** [comment]
Oh, I see, my mistake =)
