### ISSUE TITLE
Removing artboard name and exporting all iOS sizes

### ISSUE THREAD

**Issue by druid-woman** [austynmahoney/mobile-export-scripts-illustrator#14]
This was a really helpful plugin :) Saves a lot of time from manually saving all the names. One thing I noticed was that setting the artboard name was a hindrance since Apple requries specific naming conventions for the icon names.

I modified your script slightly to remove the artboard name (just included the name in the script itself), and also added all of the iOS icon sizes based on Apple's specs:
https://developer.apple.com/library/content/qa/qa1686/_index.html

Feel free to take these mods and add them to your original code if you like.

I didn't change any of the Android sections, as their naming conventions were not as clear to me as iOS.

**Here's the modifications:**
https://github.com/druid-woman/mobile-export-scripts-illustrator-ios-all

Thanks!

**Comment by austynmahoney** [comment]
This library is not just for icons, it is for any image asset used in an Android/iOS project. Your changes seem pretty specific to that one use case.

**Comment by druid-woman** [comment]
Yes, the changes I was making were specific to iOS icons exporting from a single square image. In any case, thanks for the script, it was easy for me to modify for specific needs, and will save a lot of time in the future :) Thanks! 👍
