### ISSUE TITLE
Error 13: too many closing braces

### ISSUE THREAD

**Issue by nadzimo** [austynmahoney/mobile-export-scripts-illustrator#16]
When I try to run the script i get an error:
```
Error 13: too many closing braces
line: 533
```
Using latest Illustrator CC on Windows 10

![image](https://cloud.githubusercontent.com/assets/25529064/25949795/d3050800-3669-11e7-8a99-48e36f6b3fcf.png)

**Comment by austynmahoney** [comment]
I wonder if this is a Windows thing. I've only ever used this on Illustrator CC on OSX.

Has it ever worked for you?

**Comment by austynmahoney** [comment]
Just noticed that your error has HTML code in it. When you copied the file, did you save the raw version to your machine?

**Comment by nadzimo** [comment]
Oh you are correct I saved the html file *embarassed*
It works great thanks so much!
