### ISSUE TITLE
Error with IllustratorCS6Portable

### ISSUE THREAD

**Issue by ProFive** [austynmahoney/mobile-export-scripts-illustrator#22]
I try to import scripts but it shows a messages 
![capture](https://user-images.githubusercontent.com/5170616/37946233-9342e322-31ae-11e8-903c-339855ebdc4b.PNG)

**Comment by austynmahoney** [comment]
Other people have reported similar errors when they try to copy/paste from
Github's HTML formatted page. Download the raw version and try again.

**Comment by austynmahoney** [comment]
Closing the issue due to inactivity.
