### ISSUE TITLE
Ignore layers with ! in name

### ISSUE THREAD

**Issue by bartn** [austynmahoney/mobile-export-scripts-illustrator#6]
Would be great if you could ignore layers that have an exclamation mark in their title. This way the user can control what is being exported in the assets and what not.

**Comment by austynmahoney** [comment]
Do you mean artboards?

**Comment by bartn** [comment]
Could also be implement for art-boards (or does that work already)? But initially I mean layers, so you can automatically not export background layers for example.

**Comment by austynmahoney** [comment]
Ok I see what you mean. There isn't a notion of including/excluding layers at all right now though. I don't have time to look into it anytime soon, but you are welcome to contribute.
