### ISSUE TITLE
Wrong export sizes for Android

### ISSUE THREAD

**Issue by EsbenGaarsmand** [austynmahoney/mobile-export-scripts-illustrator#9]
The sizes are wrong for android. 
See official at: http://developer.android.com/guide/practices/screens_support.html and Read at Alternative drawables.
The correct sizes should be:

    {
        name: "mdpi",
        scaleFactor: 50,
        type: "android"
    },
    {
        name: "hdpi",
        scaleFactor: 75,
        type: "android"
    },
    {
        name: "xhdpi",
        scaleFactor: 100,
        type: "android"
    },
    {
        name: "xxhdpi",
        scaleFactor: 200,
        type: "android"
    },
    {
        name: "xxxhdpi",
        scaleFactor: 300,
        type: "android"
    }

**Comment by austynmahoney** [comment]
The scripts baseline size is `xhdpi`, this changes the size scaling values. The scaling values are also percentages of `xhdpi`, which may be why you are confused.

This is what you are quoting (the math on xxhdpi is incorrect, it should be `144x144` according to the **3:4:6:8:12:16** formula.):
48x48 (1.0x baseline) for mdpi  = `4`
72x72 (1.5x) for hdpi = `6`
96x96 (2.0x) for xhdpi  = `8`
180x180 (3.0x) for xxhdpi = `12` << incorrect in the document, should be 144x144


As an example say we had a 128*128 artboard in Illustrator. When scaled by this script, here is each size:
`16x16` = 1x
mdpi: `64x64` = 4x
hdpi: `96x96` = 6x
xhdpi: `128x128` = 8x
xxhdpi: `196x192` = 12x
xxxhdpi: `256x256` = 16x

**Comment by SamDecrock** [comment]
Why is the baseline in this script xhdpi while the real baseline should be mdpi: https://developer.android.com/guide/practices/screens_support.html ??

**Comment by austynmahoney** [comment]
This question has already been addressed in the comment above. Locking the conversation.
